server:
  port: 8081

spring:
  application:
    name: publish

  kafka:
    bootstrap-servers: localhost:9093

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
